export const ADD_RECIPE_REQUEST = 'RECIPE/ADD_RECIPE_REQUEST';
export const ADD_RECIPE_SUCCESS = 'RECIPE/ADD_RECIPE_SUCCESS';
export const ADD_RECIPE_FAILURE = 'RECIPE/ADD_RECIPE_FAILURE';

export const SET_RECIPES_DATA = 'RECIPE/SET_RECIPES_FROM_FIREBASE';

